ANSI_TKL = [
    {'Key': 'Key.esc', 'Pos': [0, 0], 'Size': '1U', },
    {'Key': 'Key.f1', 'Pos': [0, 1], 'Size': '1U', },
    {'Key': 'Key.f2', 'Pos': [0, 2], 'Size': '1U', },
    {'Key': 'Key.f3', 'Pos': [0, 3], 'Size': '1U', },
    {'Key': 'Key.f4', 'Pos': [0, 4], 'Size': '1U', },
    {'Key': 'Key.f5', 'Pos': [0, 5], 'Size': '1U', },
    {'Key': 'Key.f6', 'Pos': [0, 6], 'Size': '1U', },
    {'Key': 'Key.f7', 'Pos': [0, 7], 'Size': '1U', },
    {'Key': 'Key.f8', 'Pos': [0, 8], 'Size': '1U', },
    {'Key': 'Key.f9', 'Pos': [0, 9], 'Size': '1U', },
    {'Key': 'Key.102', 'Pos': [0, 10], 'Size': '1U', },
    {'Key': 'Key.f11', 'Pos': [0, 11], 'Size': '1U', },
    {'Key': 'Key.f12', 'Pos': [0, 12], 'Size': '1U', },
    {'Key': 'Key.print_screen', 'Pos': [0, 13], 'Size': '1U', },
    {'Key': 'Key.scroll_lock', 'Pos': [0, 14], 'Size': '1U', },
    {'Key': 'Key.pause', 'Pos': [0, 15], 'Size': '1U', },

    {'Key': '`', 'Pos': [1, 0], 'Shift': '~', 'Size': '1U', },
    {'Key': '1', 'Pos': [1, 1], 'Shift': '!', 'Size': '1U', },
    {'Key': '2', 'Pos': [1, 2], 'Shift': '@', 'Size': '1U', },
    {'Key': '3', 'Pos': [1, 3], 'Shift': '#', 'Size': '1U', },
    {'Key': '4', 'Pos': [1, 4], 'Shift': '$', 'Size': '1U', },
    {'Key': '5', 'Pos': [1, 5], 'Shift': '%', 'Size': '1U', },
    {'Key': '6', 'Pos': [1, 6], 'Shift': '^', 'Size': '1U', },
    {'Key': '7', 'Pos': [1, 7], 'Shift': '&', 'Size': '1U', },
    {'Key': '8', 'Pos': [1, 8], 'Shift': '*', 'Size': '1U', },
    {'Key': '9', 'Pos': [1, 9], 'Shift': '(', 'Size': '1U', },
    {'Key': '0', 'Pos': [1, 10], 'Shift': ')', 'Size': '1U', },
    {'Key': '-', 'Pos': [1, 11], 'Shift': '_', 'Size': '1U', },
    {'Key': '=', 'Pos': [1, 12], 'Shift': '+', 'Size': '1U', },
    {'Key': 'Key.backspace', 'Pos': [1, 13], 'Size': '2U', },
    {'Key': 'Key.insert', 'Pos': [1, 14], 'Size': '1U', },
    {'Key': 'Key.home', 'Pos': [1, 15], 'Size': '1U', },
    {'Key': 'Key.page_up', 'Pos': [1, 16], 'Size': '1U', },

    {'Key': 'Key.tab', 'Pos': [2, 0], 'Size': '1.5U', },
    {'Key': 'q', 'Pos': [2, 1], 'Shift': 'Q', 'Size': '1U', },
    {'Key': 'w', 'Pos': [2, 2], 'Shift': 'W', 'Size': '1U', },
    {'Key': 'e', 'Pos': [2, 3], 'Shift': 'E', 'Size': '1U', },
    {'Key': 'r', 'Pos': [2, 4], 'Shift': 'R', 'Size': '1U', },
    {'Key': 't', 'Pos': [2, 5], 'Shift': 'T', 'Size': '1U', },
    {'Key': 'y', 'Pos': [2, 6], 'Shift': 'Y', 'Size': '1U', },
    {'Key': 'u', 'Pos': [2, 7], 'Shift': 'U', 'Size': '1U', },
    {'Key': 'i', 'Pos': [2, 8], 'Shift': 'I', 'Size': '1U', },
    {'Key': 'o', 'Pos': [2, 9], 'Shift': 'O', 'Size': '1U', },
    {'Key': 'p', 'Pos': [2, 10], 'Shift': 'P', 'Size': '1U', },
    {'Key': '[', 'Pos': [2, 11], 'Shift': '{', 'Size': '1U', },
    {'Key': ']', 'Pos': [2, 12], 'Shift': '}', 'Size': '1U', },
    {'Key': '\\', 'Pos': [2, 13], 'Shift': '|', 'Size': '1.5U', },
    {'Key': 'Key.delete', 'Pos': [2, 14], 'Size': '1U', },
    {'Key': 'Key.end', 'Pos': [2, 15], 'Size': '1U', },
    {'Key': 'Key.page_down', 'Pos': [2, 16], 'Size': '1U', },

    {'Key': 'Key.caps_lock', 'Pos': [3, 0], 'Size': '1.75U', },
    {'Key': 'a', 'Pos': [3, 1], 'Shift': 'A', 'Size': '1U', },
    {'Key': 's', 'Pos': [3, 2], 'Shift': 'S', 'Size': '1U', },
    {'Key': 'd', 'Pos': [3, 3], 'Shift': 'D', 'Size': '1U', },
    {'Key': 'f', 'Pos': [3, 4], 'Shift': 'F', 'Size': '1U', },
    {'Key': 'g', 'Pos': [3, 5], 'Shift': 'G', 'Size': '1U', },
    {'Key': 'h', 'Pos': [3, 6], 'Shift': 'H', 'Size': '1U', },
    {'Key': 'j', 'Pos': [3, 7], 'Shift': 'J', 'Size': '1U', },
    {'Key': 'k', 'Pos': [3, 8], 'Shift': 'K', 'Size': '1U', },
    {'Key': 'l', 'Pos': [3, 9], 'Shift': 'L', 'Size': '1U', },
    {'Key': ';', 'Pos': [3, 10], 'Shift': ':', 'Size': '1U', },
    {'Key': "'", 'Pos': [3, 11], 'Shift': '"', 'Size': '1U', },
    {'Key': 'Key.enter', 'Pos': [3, 12], 'Size': '2.25U', },

    {'Key': 'Key.shift', 'Pos': [4, 0], 'Size': '2.25U', },
    {'Key': 'z', 'Pos': [4, 1], 'Shift': 'Z', 'Size': '1U', },
    {'Key': 'x', 'Pos': [4, 2], 'Shift': 'X', 'Size': '1U', },
    {'Key': 'c', 'Pos': [4, 3], 'Shift': 'C', 'Size': '1U', },
    {'Key': 'v', 'Pos': [4, 4], 'Shift': 'V', 'Size': '1U', },
    {'Key': 'b', 'Pos': [4, 5], 'Shift': 'B', 'Size': '1U', },
    {'Key': 'n', 'Pos': [4, 6], 'Shift': 'N', 'Size': '1U', },
    {'Key': 'm', 'Pos': [4, 7], 'Shift': 'M', 'Size': '1U', },
    {'Key': ',', 'Pos': [4, 8], 'Shift': '<', 'Size': '1U', },
    {'Key': '.', 'Pos': [4, 9], 'Shift': '>', 'Size': '1U', },
    {'Key': '/', 'Pos': [4, 10], 'Shift': '?', 'Size': '1U', },
    {'Key': 'Key.shift_r', 'Pos': [4, 11], 'Size': '2.75U', },
    {'Key': 'Key.up', 'Pos': [4, 12], 'Size': '1U', },

    {'Key': 'Key.ctrl_l', 'Pos': [5, 0], 'Size': '1.25U', },
    {'Key': 'Key.cmd', 'Pos': [5, 1], 'Size': '1.25U', },
    {'Key': 'Key.alt_l', 'Pos': [5, 2], 'Size': '1.25U', },
    {'Key': 'Key.space', 'Pos': [5, 3], 'Size': '6.25U', },
    {'Key': 'Key.alt_gr', 'Pos': [5, 4], 'Size': '1.25U', },
    {'Key': 'Key.cmd_r', 'Pos': [5, 6], 'Size': '1.25U', },
    # Menu Key doesn't show up so ... ?
    {'Key': 'Key.ctrl_r', 'Pos': [5, 8], 'Size': '1.25U', },
    {'Key': 'Key.left', 'Pos': [5, 9], 'Size': '1U', },
    {'Key': 'Key.down', 'Pos': [5, 10], 'Size': '1U', },
    {'Key': 'Key.right', 'Pos': [5, 11], 'Size': '1U', },
]
