ANSI_TKL = [
    {'Key': 'Key.esc', 'Pos': [0, 0], },
    {'Key': 'Key.f1', 'Pos': [0, 1], },
    {'Key': 'Key.f2', 'Pos': [0, 2], },
    {'Key': 'Key.f3', 'Pos': [0, 3], },
    {'Key': 'Key.f4', 'Pos': [0, 4], },
    {'Key': 'Key.f5', 'Pos': [0, 5], },
    {'Key': 'Key.f6', 'Pos': [0, 6], },
    {'Key': 'Key.f7', 'Pos': [0, 7], },
    {'Key': 'Key.f8', 'Pos': [0, 8], },
    {'Key': 'Key.f9', 'Pos': [0, 9], },
    {'Key': 'Key.102', 'Pos': [0, 10], },
    {'Key': 'Key.f11', 'Pos': [0, 11], },
    {'Key': 'Key.f12', 'Pos': [0, 12], },
    {'Key': 'Key.print_screen', 'Pos': [0, 13], },
    {'Key': 'Key.scroll_lock', 'Pos': [0, 14], },
    {'Key': 'Key.pause', 'Pos': [0, 15], },

    {'Key': '`', 'Pos': [1, 0], 'Shift': '~', },
    {'Key': '1', 'Pos': [1, 1], 'Shift': '!', },
    {'Key': '2', 'Pos': [1, 2], 'Shift': '@', },
    {'Key': '3', 'Pos': [1, 3], 'Shift': '#', },
    {'Key': '4', 'Pos': [1, 4], 'Shift': '$', },
    {'Key': '5', 'Pos': [1, 5], 'Shift': '%', },
    {'Key': '6', 'Pos': [1, 6], 'Shift': '^', },
    {'Key': '7', 'Pos': [1, 7], 'Shift': '&', },
    {'Key': '8', 'Pos': [1, 8], 'Shift': '*', },
    {'Key': '9', 'Pos': [1, 9], 'Shift': '(', },
    {'Key': '0', 'Pos': [1, 10], 'Shift': ')', },
    {'Key': '-', 'Pos': [1, 11], 'Shift': '_', },
    {'Key': '=', 'Pos': [1, 12], 'Shift': '+', },
    {'Key': 'Key.backspace', 'Pos': [1, 13], 'Size': '2U', },
    {'Key': 'Key.insert', 'Pos': [1, 14], },
    {'Key': 'Key.home', 'Pos': [1, 15], },
    {'Key': 'Key.page_up', 'Pos': [1, 16], },

    {'Key': 'Key.tab', 'Pos': [2, 0], 'Size': '1.5U', },
    {'Key': 'q', 'Pos': [2, 1], 'Shift': 'Q', },
    {'Key': 'w', 'Pos': [2, 2], 'Shift': 'W', },
    {'Key': 'e', 'Pos': [2, 3], 'Shift': 'E', },
    {'Key': 'r', 'Pos': [2, 4], 'Shift': 'R', },
    {'Key': 't', 'Pos': [2, 5], 'Shift': 'T', },
    {'Key': 'y', 'Pos': [2, 6], 'Shift': 'Y', },
    {'Key': 'u', 'Pos': [2, 7], 'Shift': 'U', },
    {'Key': 'i', 'Pos': [2, 8], 'Shift': 'I', },
    {'Key': 'o', 'Pos': [2, 9], 'Shift': 'O', },
    {'Key': 'p', 'Pos': [2, 10], 'Shift': 'P', },
    {'Key': '[', 'Pos': [2, 11], 'Shift': '{', },
    {'Key': ']', 'Pos': [2, 12], 'Shift': '}', },
    {'Key': '\\', 'Pos': [2, 13], 'Shift': '|', 'Size': '1.5U', },
    {'Key': 'Key.delete', 'Pos': [2, 14], },
    {'Key': 'Key.end', 'Pos': [2, 15], },
    {'Key': 'Key.page_down', 'Pos': [2, 16], },

    {'Key': 'Key.caps_lock', 'Pos': [3, 0], 'Size': '1.75U', },
    {'Key': 'a', 'Pos': [3, 1], 'Shift': 'A', },
    {'Key': 's', 'Pos': [3, 2], 'Shift': 'S', },
    {'Key': 'd', 'Pos': [3, 3], 'Shift': 'D', },
    {'Key': 'f', 'Pos': [3, 4], 'Shift': 'F', },
    {'Key': 'g', 'Pos': [3, 5], 'Shift': 'G', },
    {'Key': 'h', 'Pos': [3, 6], 'Shift': 'H', },
    {'Key': 'j', 'Pos': [3, 7], 'Shift': 'J', },
    {'Key': 'k', 'Pos': [3, 8], 'Shift': 'K', },
    {'Key': 'l', 'Pos': [3, 9], 'Shift': 'L', },
    {'Key': ';', 'Pos': [3, 10], 'Shift': ':', },
    {'Key': "'", 'Pos': [3, 11], 'Shift': '"', },
    {'Key': 'Key.enter', 'Pos': [3, 12], 'Size': '2.25U', },

    {'Key': 'Key.shift', 'Pos': [4, 0], 'Size': '2.25U', },
    {'Key': 'z', 'Pos': [4, 1], 'Shift': 'Z', },
    {'Key': 'x', 'Pos': [4, 2], 'Shift': 'X', },
    {'Key': 'c', 'Pos': [4, 3], 'Shift': 'C', },
    {'Key': 'v', 'Pos': [4, 4], 'Shift': 'V', },
    {'Key': 'b', 'Pos': [4, 5], 'Shift': 'B', },
    {'Key': 'n', 'Pos': [4, 6], 'Shift': 'N', },
    {'Key': 'm', 'Pos': [4, 7], 'Shift': 'M', },
    {'Key': ',', 'Pos': [4, 8], 'Shift': '<', },
    {'Key': '.', 'Pos': [4, 9], 'Shift': '>', },
    {'Key': '/', 'Pos': [4, 10], 'Shift': '?', },
    {'Key': 'Key.shift_r', 'Pos': [4, 11], 'Size': '2.75U', },
    {'Key': 'Key.up', 'Pos': [4, 12], },

    {'Key': 'Key.ctrl_l', 'Pos': [5, 0], 'Size': '1.25U', },
    {'Key': 'Key.cmd', 'Pos': [5, 1], 'Size': '1.25U', },
    {'Key': 'Key.alt_l', 'Pos': [5, 2], 'Size': '1.25U', },
    {'Key': 'Key.space', 'Pos': [5, 3], 'Size': '6.25U', },
    {'Key': 'Key.alt_gr', 'Pos': [5, 4], 'Size': '1.25U', },
    {'Key': 'Key.cmd_r', 'Pos': [5, 6], 'Size': '1.25U', },
    # Menu Key doesn't show up so ... ?
    {'Key': 'Key.ctrl_r', 'Pos': [5, 8], 'Size': '1.25U', },
    {'Key': 'Key.left', 'Pos': [5, 9], },
    {'Key': 'Key.down', 'Pos': [5, 10], },
    {'Key': 'Key.right', 'Pos': [5, 11], },
]
