ANSI_TKL = [
    {'Key': 'Key.esc', 'Pos': [0, 0], 'Size': [1, 1], },
    {'Key': "SPACER", 'Pos': [0, 1], 'Size': [1, 1], },   # Spacer
    {'Key': 'Key.f1', 'Pos': [0, 2], 'Size': [1, 1], },
    {'Key': 'Key.f2', 'Pos': [0, 3], 'Size': [1, 1], },
    {'Key': 'Key.f3', 'Pos': [0, 4], 'Size': [1, 1], },
    {'Key': 'Key.f4', 'Pos': [0, 5], 'Size': [1, 1], },
    {'Key': "SPACER", 'Pos': [0, 6], 'Size': [1, 0.5], },  # Spacer
    {'Key': 'Key.f5', 'Pos': [0, 6.5], 'Size': [1, 1], },
    {'Key': 'Key.f6', 'Pos': [0, 7.5], 'Size': [1, 1], },
    {'Key': 'Key.f7', 'Pos': [0, 8.5], 'Size': [1, 1], },
    {'Key': 'Key.f8', 'Pos': [0, 9.5], 'Size': [1, 1], },
    {'Key': "SPACER", 'Pos': [0, 10.5], 'Size': [1, 0.5], },  # Spacer
    {'Key': 'Key.f9', 'Pos': [0, 11], 'Size': [1, 1], },
    {'Key': 'Key.f10', 'Pos': [0, 12], 'Size': [1, 1], },
    {'Key': 'Key.f11', 'Pos': [0, 13], 'Size': [1, 1], },
    {'Key': 'Key.f12', 'Pos': [0, 14], 'Size': [1, 1], },
    {'Key': "SPACER", 'Pos': [0, 15], 'Size': [1, 0.25], },  # Spacer
    {'Key': 'Key.print_screen', 'Pos': [0, 15.25], 'Size': [1, 1], },
    {'Key': 'Key.scroll_lock', 'Pos': [0, 16.25], 'Size': [1, 1], },
    {'Key': 'Key.pause', 'Pos': [0, 17.25], 'Size': [1, 1], },

    {'Key': "SPACER", 'Pos': [1, 0], 'Size': [0.5, 18.25]},

    {'Key': '`', 'Pos': [2, 0], 'Shift': '~', 'Size': [1, 1], },
    {'Key': '1', 'Pos': [2, 1], 'Shift': '!', 'Size': [1, 1], },
    {'Key': '2', 'Pos': [2, 2], 'Shift': '@', 'Size': [1, 1], },
    {'Key': '3', 'Pos': [2, 3], 'Shift': '#', 'Size': [1, 1], },
    {'Key': '4', 'Pos': [2, 4], 'Shift': '$', 'Size': [1, 1], },
    {'Key': '5', 'Pos': [2, 5], 'Shift': '%', 'Size': [1, 1], },
    {'Key': '6', 'Pos': [2, 6], 'Shift': '^', 'Size': [1, 1], },
    {'Key': '7', 'Pos': [2, 7], 'Shift': '&', 'Size': [1, 1], },
    {'Key': '8', 'Pos': [2, 8], 'Shift': '*', 'Size': [1, 1], },
    {'Key': '9', 'Pos': [2, 9], 'Shift': '(', 'Size': [1, 1], },
    {'Key': '0', 'Pos': [2, 10], 'Shift': ')', 'Size': [1, 1], },
    {'Key': '-', 'Pos': [2, 11], 'Shift': '_', 'Size': [1, 1], },
    {'Key': '=', 'Pos': [2, 12], 'Shift': '+', 'Size': [1, 1], },
    {'Key': 'Key.backspace', 'Pos': [2, 13], 'Size': [1, 2], },
    {'Key': "SPACER", 'Pos': [2, 15], 'Size': [1, 0.25], },  # Spacer
    {'Key': 'Key.insert', 'Pos': [2, 15.25], 'Size': [1, 1], },
    {'Key': 'Key.home', 'Pos': [2, 16.25], 'Size': [1, 1], },
    {'Key': 'Key.page_up', 'Pos': [2, 17.25], 'Size': [1, 1], },

    {'Key': 'Key.tab', 'Pos': [3, 0], 'Size': [1, 1.5], },
    {'Key': 'q', 'Pos': [3, 1.5], 'Shift': 'Q', 'Size': [1, 1], },
    {'Key': 'w', 'Pos': [3, 2.5], 'Shift': 'W', 'Size': [1, 1], },
    {'Key': 'e', 'Pos': [3, 3.5], 'Shift': 'E', 'Size': [1, 1], },
    {'Key': 'r', 'Pos': [3, 4.5], 'Shift': 'R', 'Size': [1, 1], },
    {'Key': 't', 'Pos': [3, 5.5], 'Shift': 'T', 'Size': [1, 1], },
    {'Key': 'y', 'Pos': [3, 6.5], 'Shift': 'Y', 'Size': [1, 1], },
    {'Key': 'u', 'Pos': [3, 7.5], 'Shift': 'U', 'Size': [1, 1], },
    {'Key': 'i', 'Pos': [3, 8.5], 'Shift': 'I', 'Size': [1, 1], },
    {'Key': 'o', 'Pos': [3, 9.5], 'Shift': 'O', 'Size': [1, 1], },
    {'Key': 'p', 'Pos': [3, 10.5], 'Shift': 'P', 'Size': [1, 1], },
    {'Key': '[', 'Pos': [3, 11.5], 'Shift': '{', 'Size': [1, 1], },
    {'Key': ']', 'Pos': [3, 12.5], 'Shift': '}', 'Size': [1, 1], },
    {'Key': '\\', 'Pos': [3, 13.5], 'Shift': '|', 'Size': [1, 1.5], },
    {'Key': "SPACER", 'Pos': [3, 15], 'Size': [1, 0.25], },  # Spacer
    {'Key': 'Key.delete', 'Pos': [3, 15.25], 'Size': [1, 1], },
    {'Key': 'Key.end', 'Pos': [3, 16.25], 'Size': [1, 1], },
    {'Key': 'Key.page_down', 'Pos': [3, 17.25], 'Size': [1, 1], },

    {'Key': 'Key.caps_lock', 'Pos': [4, 0], 'Size': [1, 1.75], },
    {'Key': 'a', 'Pos': [4, 1.75], 'Shift': 'A', 'Size': [1, 1], },
    {'Key': 's', 'Pos': [4, 2.75], 'Shift': 'S', 'Size': [1, 1], },
    {'Key': 'd', 'Pos': [4, 3.75], 'Shift': 'D', 'Size': [1, 1], },
    {'Key': 'f', 'Pos': [4, 4.75], 'Shift': 'F', 'Size': [1, 1], },
    {'Key': 'g', 'Pos': [4, 5.75], 'Shift': 'G', 'Size': [1, 1], },
    {'Key': 'h', 'Pos': [4, 6.75], 'Shift': 'H', 'Size': [1, 1], },
    {'Key': 'j', 'Pos': [4, 7.75], 'Shift': 'J', 'Size': [1, 1], },
    {'Key': 'k', 'Pos': [4, 8.75], 'Shift': 'K', 'Size': [1, 1], },
    {'Key': 'l', 'Pos': [4, 9.75], 'Shift': 'L', 'Size': [1, 1], },
    {'Key': ';', 'Pos': [4, 10.75], 'Shift': ':', 'Size': [1, 1], },
    {'Key': "'", 'Pos': [4, 11.75], 'Shift': '"', 'Size': [1, 1], },
    {'Key': 'Key.enter', 'Pos': [4, 12.75], 'Size': [1, 2.25], },

    {'Key': 'Key.shift', 'Pos': [5, 0], 'Size': [1, 2.25], },
    {'Key': 'z', 'Pos': [5, 2.25], 'Shift': 'Z', 'Size': [1, 1], },
    {'Key': 'x', 'Pos': [5, 3.25], 'Shift': 'X', 'Size': [1, 1], },
    {'Key': 'c', 'Pos': [5, 4.25], 'Shift': 'C', 'Size': [1, 1], },
    {'Key': 'v', 'Pos': [5, 5.25], 'Shift': 'V', 'Size': [1, 1], },
    {'Key': 'b', 'Pos': [5, 6.25], 'Shift': 'B', 'Size': [1, 1], },
    {'Key': 'n', 'Pos': [5, 7.25], 'Shift': 'N', 'Size': [1, 1], },
    {'Key': 'm', 'Pos': [5, 8.25], 'Shift': 'M', 'Size': [1, 1], },
    {'Key': ',', 'Pos': [5, 9.25], 'Shift': '<', 'Size': [1, 1], },
    {'Key': '.', 'Pos': [5, 10.25], 'Shift': '>', 'Size': [1, 1], },
    {'Key': '/', 'Pos': [5, 11.25], 'Shift': '?', 'Size': [1, 1], },
    {'Key': 'Key.shift_r', 'Pos': [5, 12.25], 'Size': [1, 2.75], },
    {'Key': "SPACER", 'Pos': [5, 15], 'Size': [1, 1.25], },  # Spacer
    {'Key': 'Key.up', 'Pos': [5, 16.25], 'Size': [1, 1], },

    {'Key': 'Key.ctrl_l', 'Pos': [6, 0], 'Size': [1, 1.25], },
    {'Key': 'Key.cmd', 'Pos': [6, 1.25], 'Size': [1, 1.25], },
    {'Key': 'Key.alt_l', 'Pos': [6, 2.5], 'Size': [1, 1.25], },
    {'Key': 'Key.space', 'Pos': [6, 3.75], 'Size': [1, 6.25], },
    {'Key': 'Key.alt_gr', 'Pos': [6, 10], 'Size': [1, 1.25], },
    {'Key': 'Key.cmd_r', 'Pos': [6, 11.25], 'Size': [1, 1.25], },
    {'Key': "SPACER", 'Pos': [6, 12.5], 'Size': [1, 1.25], },  # Spacer (Menu Key doesn't show?)
    {'Key': 'Key.ctrl_r', 'Pos': [6, 13.75], 'Size': [1, 1.25], },
    {'Key': "SPACER", 'Pos': [6, 15.75], 'Size': [1, 0.25], },  # Spacer
    {'Key': 'Key.left', 'Pos': [6, 15.25], 'Size': [1, 1], },
    {'Key': 'Key.down', 'Pos': [6, 16.25], 'Size': [1, 1], },
    {'Key': 'Key.right', 'Pos': [6, 17.25], 'Size': [1, 1], },
]
